# Generated by Django 2.0.5 on 2018-05-31 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20180517_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePhoto',
            fields=[
                ('RoutePhotoID', models.AutoField(primary_key=True, serialize=False)),
                ('PhotoURL', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='TagPlace',
            fields=[
                ('TagPlaceID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TagRoute',
            fields=[
                ('TagRouteID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='Location',
        ),
        migrations.AddField(
            model_name='place',
            name='Latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='place',
            name='Longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='place',
            name='IconURL',
            field=models.URLField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='place',
            name='IsPublic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='AvatarURL',
            field=models.CharField(default='http://fastestlaps.com/ui_images/default_avatar.png', max_length=3000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='route',
            name='IsPublic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tagroute',
            name='RouteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Route'),
        ),
        migrations.AddField(
            model_name='tagroute',
            name='TagID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tag'),
        ),
        migrations.AddField(
            model_name='tagplace',
            name='PlaceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Place'),
        ),
        migrations.AddField(
            model_name='tagplace',
            name='TagID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tag'),
        ),
        migrations.AddField(
            model_name='routephoto',
            name='RouteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Route'),
        ),
        migrations.AddField(
            model_name='routephoto',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
